In [25]:
# Data manipulation
import numpy as np
import pandas as pd

# Plotting 
import matplotlib.pyplot as plt

# Statistical calculation
import scipy.stats as scs

# Data fetching (Stock prices)
import yfinance as yf #can use other free APIs also

# Time
import datetime as dt

In [26]:
rfr = 0.04 # risk free rate
time = 0.75 # 0.75 years... for dt, i will divide by n_steps(no of working days in a year)
sigma = 0.3 #volatility / std deviation
S0 = 50 #stock price
n_steps = 252 
n_sims = 50000 
K=45 #strike price

In [27]:
dt = time/n_steps

In [28]:
d = (rfr - 0.5 * sigma**2) * (dt)

a = sigma *np.sqrt(dt)

x = np.random.normal(0,1,(n_sims,n_steps)) # 0 mean, 1 std. dev, x is an array of dim (n_sims * n_steps)

In [29]:
S = np.zeros((n_sims,n_steps)) # stock price array 
S[:,0] += S0 # initial value

# brownian motion formula for n_steps
for i in range(1,n_steps):
    S[:,i] += S[:,i-1] * np.exp(d + a*x[:,i])

S

array([[50.        , 50.47760211, 50.93022852, ..., 40.12027687,
        40.99361809, 41.3070533 ],
       [50.        , 50.52640853, 49.68301368, ..., 56.89154878,
        55.16667263, 55.95938889],
       [50.        , 49.8056335 , 49.74530352, ..., 67.37067875,
        67.38602446, 66.25432888],
       ...,
       [50.        , 50.13882277, 50.17273587, ..., 45.75564138,
        44.79439436, 44.03235473],
       [50.        , 51.2396448 , 52.28563228, ..., 58.93719334,
        58.86600527, 57.34914356],
       [50.        , 50.69677488, 50.89386232, ..., 38.55167234,
        38.16091989, 38.33192784]])

In [30]:
call_payoff = S[:,-1]-K

#since call_payoff cant be negative

for i in range(len(call_payoff)):
    if call_payoff[i] < 0:
        call_payoff[i]=0
call_payoff

array([ 0.        , 10.95938889, 21.25432888, ...,  0.        ,
       12.34914356,  0.        ])

In [31]:
put_payoff = K- S[:,-1]

#since put_payoff cant be negative

for i in range(len(put_payoff)):
    if put_payoff[i] < 0:
        put_payoff[i]=0
put_payoff

array([3.6929467 , 0.        , 0.        , ..., 0.96764527, 0.        ,
       6.66807216])

In [32]:
call_payoff_final = np.mean(call_payoff)
put_payoff_final = np.mean(put_payoff)

In [33]:
call_payoff_final

8.895104182169483

In [34]:
put_payoff_final

2.359521187521903

In [35]:
call_opt_price = call_payoff_final*np.exp(-rfr*time) #time in already in years
put_opt_price = put_payoff_final*np.exp(-rfr*time) 

In [36]:
call_opt_price

8.63221412403503

In [37]:
put_opt_price

#strike price is lesser than stock price, so, it's intuitive that put option is cheaper than call option

#also, as n_sims increases, the options value found here and those in bsm model get closer to each other 

2.2897867977437025